### ISSUE TITLE
[Server Crash]: ClassNotFoundException: CharcoalPit.core.ServerProxy

### ISSUE THREAD

**Issue by Lanse505** [EnderiumSmith/CharcoalPit#1]
Seems to be a straight-up crash on server load.
Caused by a ClassNotFoundException on your "CharcoalPit.core.ServerProxy"

Crashlog:
https://gist.github.com/Lanse505/0b1b3bc1555fa0aa591aa7d770b3d2e0

**Comment by EnderiumSmith** [comment]
its a typo. to note: serverProxy is only called on dedicated server
