### ISSUE TITLE
add pottery kiln

### ISSUE THREAD

**Issue by EnderiumSmith** [EnderiumSmith/CharcoalPit#11]
it appears to be "kiln" not "klin"

need ideas for pottery kiln structure

**Comment by Ash70** [comment]
Just a few ideas.

Melting ingots in a claycast into toolheads. And then crafting the head with a stick (and optionally a binding) into a tool like axes, shovels, etc.

Replacing the wooden bowl with a clay bowl. Perhaps add other forms of pottery like flowerpots, large fluid containers.

Also make hardened clay in the kiln. This includes bricks.

Maybe a bit much but; smelt sand into liquid glass which can then be shaped into blocks, panes and bottles somehow.

**Comment by EnderiumSmith** [comment]
how would automation work with the kiln? its a tile entity that holds items. and what would the block you place first be?

**Comment by Ash70** [comment]
I didn't think it through that well and just spouted some ideas. Disregard/reject as you wish or as needed :-)

**Comment by XvBUSHvX** [comment]
I have recently discovered a mod from 1.7.10 named TerraFirmaCraft. I don't know if you are familiar with it or not. It has a very loyal fan base, but it isn't hosted on the Curseforge site. It was by sheer good fortune that I happened upon it. The mod has many, many, changes that affect the early game, resource gathering, and processing. 

Based on what I am starting to understand about Charcoal Pit thus far, I think if you were to look into that mod, as well as a few of the addons for it, you would be able to draw a great deal of inspiration for what you are wanting to accomplish with the kiln. 

The first being the "Pit Kiln" and then from there I'd suggest a multiblock structure constructed of some sort of brick? Hardened Clay? Perhaps even a different type of clay made with clay blocks and another material? For the Kiln bricks, I'd suggest bricks made of clay and sand, which if I understand is how refractive bricks are made. 

I'm picturing a 1x3 hole in the ground (non-combustible material), with a hollow 3x3 pattern of bricks built above two of the holes where the center hole lines up with one of the end holes in the ground. Provide a "grate" block to place over the hollow section. then the next layer of the kiln will be a 7 block horseshoe pattern (opposite the exposed hole in the ground) with another "grate piece filling in the outer space in the U shape to act as a door. then the third layer would be a hollow + pattern centered over the rest of the hollow area's. 

The following are some images I put together to represent what I'm trying to describe. The bricks are the refractive bricks, the stone slab is the grate, and the gate would be where the kiln door would go. Players would have to load blocks of wood, coal, or charcoal into the pit and light it (possibly even cover the hole with something?) then be able to place the items they wish to bake into the kiln from the door side, and smoke particles could exit the top. 

However, if you aren't familiar with TFC I strongly suggest you look it up on YouTube there are several good lets plays, and it fits perfectly with this mod and the type of pack I am hoping to use this mod in. 

![2017-10-19_21 43 02](https://user-images.githubusercontent.com/32846606/31803004-f91ad872-b516-11e7-90ba-2c093a80a66f.png)
![2017-10-19_21 43 10](https://user-images.githubusercontent.com/32846606/31803005-f94844ce-b516-11e7-8b2d-58afb1c526a0.png)
![2017-10-19_21 43 22](https://user-images.githubusercontent.com/32846606/31803006-f956a582-b516-11e7-8ca1-918e2c423248.png)
![2017-10-19_21 47 35](https://user-images.githubusercontent.com/32846606/31803064-57396eaa-b517-11e7-9a78-904d69c054c2.png)
![2017-10-19_21 45 39](https://user-images.githubusercontent.com/32846606/31803009-f9842f0c-b516-11e7-859e-34190c019933.png)
![2017-10-19_21 45 48](https://user-images.githubusercontent.com/32846606/31803010-f99490c2-b516-11e7-800a-5e85d33ceb7a.png)


Anyways just food for thought hope it helped.

**Comment by EnderiumSmith** [comment]
I know about TFC. The mod is inspired by its charcoal pits. I have decided that the kiln will be a pit kiln like the TFC one but this could be a tier 2.
