### ISSUE TITLE
[1.12.2] Crash on Game Start

### ISSUE THREAD

**Issue by MasterEnderman** [EnderiumSmith/CharcoalPit#14]
Added Charcoal Pit to my Modpack and it's crashing before it reaches the main menu.

Forge: 14.23.0.2512
Charcoal Pit: 1.4_12
Crash Report: https://pastebin.com/Wdpea9mR

**Comment by MasterEnderman** [comment]
Fixed it by disabling the removal of the furnace recipe. Maybe considering turning this option off by default.

**Comment by XvSkItZvX** [comment]
Hey homie! This is what my error was too, worked like a charm. I'm going to comment on the CF page so, hopefully, people will see it if they don't look in here. try to keep you from getting spammed with it. I'll take a few to look over the mod and see if I can offer and ideas for your other topics.
