### ISSUE TITLE
[1.12.2] 1.5_bata Servercrash at startup

### ISSUE THREAD

**Issue by lukiono** [EnderiumSmith/CharcoalPit#16]
Greetings,

Version 1.5_bata crashes my server
Crash report here:
https://paste.ee/p/njrQh

Used Forge version: 1.12.2 - 14.23.0.2528
Also using latest available foamfix-anarchy

Kind regards

**Comment by GarisHallorand** [comment]
Hello there, i have the same problem, using forge 1.12.2 14.23.0.2529.

Crash report: [https://pastebin.com/DfJB6iRw](https://pastebin.com/DfJB6iRw)

**Comment by EnderiumSmith** [comment]
Apparently TESRs should be bound in client proxy, not the block class. I wont release another beta. It will be fixed in the release.
