### ISSUE TITLE
[1.12.2] On server: Player crashed when destroying unlit pottery kiln

### ISSUE THREAD

**Issue by lukiono** [EnderiumSmith/CharcoalPit#23]
Greetings,

first thanks for your ongoing work.

Version of Mod: 1.5 Release Version

A player on my server crashed when i instructed him the new pottery kiln. i didnt lit it, (the kiln), up but breaked it with the hand. the client of him crashed instantly and the following error was printed:

https://paste.ee/p/xFqm8

Kind regards

**Comment by EnderiumSmith** [comment]
does it happen every time? it seems like the TESR is ticked after breaking the kiln. it should be removed the same tick.

**Comment by lukiono** [comment]
Yes, happens everytime for every player when they stand in the range. Only the players standing near crashes. the player who breaks the unfinished and finished kiln doesnt crash
