### ISSUE TITLE
Incompatibility with better with mods

### ISSUE THREAD

**Issue by Octopork** [EnderiumSmith/CharcoalPit#24]
better with mods allows placing clay down as a single piece of clay to be cooked in it's own kiln. as a result it's impossible to place clay down for use in the charcoal pit kiln. given by default furnace recipes are disabled it is no longer possible to create bricks.

BWM issue
https://github.com/BetterWithMods/BetterWithMods/issues/645

**Comment by Octopork** [comment]
side note, this would be a great target for some integration(nether sludge, crucible pots as examples). 

Your kiln is early game, cooks in bulk and is probably faster. 

BWM Kiln takes a bit of later game infrastructure, only does one at a time but has no running cost once set up.  

They could coexist quite well.

**Comment by EnderiumSmith** [comment]
What should i do? set the event to higher priority so it runs before BWM? add unfired clay bricks? how would i craft them?

**Comment by Octopork** [comment]
I suggested that bwm to give this mod priority if shift is pressed. I.e

Right click = bwm 
Shift + right click = charcoal pit.

Not perfect but it would allow the two mods to function.

**Comment by DaedalusGame** [comment]
I suggest running at higher priority, as your mod is more specific about the clicks, so the shift-rclick will run first, and if it doesn't do anything (because shift isn't pressed or whatever), the clay brick from bwm will be placed instead.

**Comment by EnderiumSmith** [comment]
It was set to Lowest. Changed it to High.
