### ISSUE TITLE
[Bug] Crash with disablied registration of creosote

### ISSUE THREAD

**Issue by OneEyeMaker** [EnderiumSmith/CharcoalPit#25]
Hello.
When I disable registration of creosote in configuration (I already have creosote from Immersive Engineering), I get this crash:
https://pastebin.com/1duf54Rt

It seems like you didn't tested all config options. With disabled creosote ```FluidsRegistry``` isn't initialized.
So, you need add [this](https://github.com/EnderiumSmith/CharcoalPit/blob/master/src/main/java/charcoalPit/core/CommonProxy.java#L38) check [here](https://github.com/EnderiumSmith/CharcoalPit/blob/master/src/main/java/charcoalPit/core/ClientProxy.java#L25-L32)

Please, fix this bug *ASAP*.

Thank you for your work!

**Comment by EnderiumSmith** [comment]
FluidsRegistry doesnt need to be initialized.

CharcoalPit loads before IE. rename the fire so it loads after.

I will change it so it autodisables when another mod adds it.
