### ISSUE TITLE
Add metal smelting mechanic

### ISSUE THREAD

**Issue by EnderiumSmith** [EnderiumSmith/CharcoalPit#27]
- [x] Ore kiln

- [x] Bloomery

**Comment by EnderiumSmith** [comment]
@Ash70 ore recipes are more complex. i will add minetweaker support at a later date. if you are making a pack you could change the recipes with a custom mod for now.

Currently the kiln smelts: Copper, Zinc, Silver, Tin, Gold, Lead, Bismuth, Bronze, Brass, Bismuth Bronze, Black Bronze and Electrum
In addition the bloomery smelts: Aluminium, Aluminum, Titanium, Iron, Nickel, Platinum, Invar and Constantan

**Comment by Ash70** [comment]
Fair enough. But would you consider a temporary solution for now (if it is not too much work).
I suspect you check for any oredictionary **oreX** and turn it into the **ingotX** (e.g. oreIron turns into ingotIron) If so, could you add a configoption that allows changing that?

S:oredictprefix=ingot

That way I can control which ores turn into their respective result without having to change the oredict of the ingots (which would mess up all recipes in the game).

**Comment by Ash70** [comment]
@EnderiumSmith  also, just for reference. These are the (average) melting temperatures in Celsius. The point at which a kiln could no longer melt them would be around 1100, so uranium. The way you arranged it seems fine, with the exception of aluminium which has a low melting temp.

Tin 230
Lead 327
Zinc 419
Aluminium 660
Silver 900
Bronze 1000
Gold 1063
Copper 1084
Uranium 1100 ------------------------------
Constantan 1210
Iron 1300
Invar 1427
Nickel 1500
Steel 1500
Titanium 1668
Platinum 1700
Osmium 3000
Tungsten 3400

**Comment by darthvader45** [comment]
Huh, I was curious about smelting bronze, as I needed a few blocks for the bloomery hatch.  I tossed three copper and one tin into a clay pot, as well as four coal.  Maybe I need something else?

Edit:  Okay, have 8 total ore in the clay pot (6 copper 2 tin), as well as 4 coal providing eight units of fuel.  The tooltip is green, which I assume means I have the correct ingredients and amounts.  How does one start the process?

Edit2: Okay, figured it out.  For anyone else a bit confused, its done the same way as the pottery kiln, except with a filled clay pot, using ore/ingots and fuel (coal/charcoal).  Maybe I could make a wiki describing each process, so no one gets confused?
