### ISSUE TITLE
All mod blocks are unavailable

### ISSUE THREAD

**Issue by OneEyeMaker** [EnderiumSmith/CharcoalPit#29]
Hello. 
The title says it all. Creosote collectors are unavailable. In JEI ones look like untextured blocks without localization; its' name starting with ```tile.jei:```.

I can't say, what exactly causes this behavior (because this repo isn't updated to last version). My guesses:
 - either you renamed/moved blockstate file (and now collectors look like as blocks without associated blockstate)
 - or you messed with JEI handler.

In any case, please fix it.

MC 1.12.2
Forge build 2537-2540
Mod version: 1.7

**Comment by EnderiumSmith** [comment]
Creosote funnels have nothing to do with JEI. try on a fresh install with the latest JEI.

**Comment by OneEyeMaker** [comment]
I found, that this issue occurs only if AppleSkin and JEI are installed with this mod.
I already reported this to author of AppleSkin:
https://github.com/squeek502/AppleSkin/issues/18

**Comment by squeek502** [comment]
@EnderiumSmith it might be worth taking a look at my comments in https://github.com/squeek502/AppleSkin/issues/18. One thing I noticed that you might want to look into is that your mod isn't using the `RegistryEvent`/`ModelRegistryEvent` events to register your items/models. See the [Forge docs on registries](https://mcforge.readthedocs.io/en/latest/concepts/registries/) and [McJty's tutorial](https://wiki.mcjty.eu/modding/index.php/Render_Item_Basic-1.12).

Not sure if it's related to the load order problem, but still might be worth checking out.

**Comment by Efimero** [comment]
I found this issue still affects the current latest version, but this issue is closed?
does that mean it is fixed on the next version?
