### ISSUE TITLE
[1.12.2] Servercrash with Version 1.8

### ISSUE THREAD

**Issue by lukiono** [EnderiumSmith/CharcoalPit#31]
Greetings,

At serverstart it crashes.

Mod version: Latest (1.8)
Forge Version: 1.12.2 - 14.23.1.2555

Crash report:
https://ybin.me/p/cf4dd6cbe20f4bdd#+KZfGYpShhpaDIk9AtFLDLseOSSPScMebCz8/oYlKDY=

Kind regards,
Lukas

**Comment by EnderiumSmith** [comment]
why does the server crashes every time i add something? i should probably test it before uploading.

**Comment by lukiono** [comment]
Thanks for your work =)
