### ISSUE TITLE
[suggestion] early game flint & steel replacement

### ISSUE THREAD

**Issue by Ash70** [EnderiumSmith/CharcoalPit#35]
Esp. now that ore smelting is about to become part of the kiln. I think it would fit to add a simple, early game, replacement for flint & steel to light the kiln; since flint & steel needs iron.
Perhaps some sort of[ bow drill](https://en.wikipedia.org/wiki/Bow_drill) with low durability and low chance? Or (shift) right-clicking a torch on the kiln (simplest solution I guess?)

**Comment by EnderiumSmith** [comment]
the code for the ore kiln is complete. this was next on the list along with dyed vessels.
I was thinking about just using 2 sticks like in TFC. which should i go with? the bow drill would require spiders

**Comment by Ash70** [comment]
2 sticks will do I think, no need to over-complicate things. ;)
