### ISSUE TITLE
Ore recipes only removed on vanila furnace

### ISSUE THREAD

**Issue by PandaBoy444** [EnderiumSmith/CharcoalPit#38]
When you choose the option to remove vanilla ore to ingot smelting it does not remove it correctly or something because other mods still think its there. I can always remove them with craftTweaker but id prefer it to be a part of the mod in general.

**Comment by EnderiumSmith** [comment]
I dont really mind of an electric furnace can smelt ore. you have ore doubling by that point. Removing recipes is kinda confusing anyway. its better to do it with minetweaker
