### ISSUE TITLE
Charcoal pit is causing fuel tooltip problems & breaks some JEI integrations.

### ISSUE THREAD

**Issue by Claycorp** [EnderiumSmith/CharcoalPit#4]
https://pastebin.com/Lb6zsv2m
https://pastebin.com/J3v56UiA

**Comment by EnderiumSmith** [comment]
it seems to be caused by a bucket with a null fluidstack. i'll have to find a better way to check the fluid inside a container.

is this a problem in both 1.10 and 1.11?

**Comment by Claycorp** [comment]
I'm not sure. I'm only working with 1.10 currently.

**Comment by EnderiumSmith** [comment]
i uploaded a new version. i cant reproduce the error so i dont know if it works. test it yourself.

**Comment by Claycorp** [comment]
I sure can. I'll get back to ya in a bit with that.

**Comment by Claycorp** [comment]
Looks fixed! 
Thanks!
