### ISSUE TITLE
[request] Make the check for solid sides into a check for solid blockfaceshape instead

### ISSUE THREAD

**Issue by DaedalusGame** [EnderiumSmith/CharcoalPit#42]
Right now, the check for your charcoal/coke pile blocks checks for solid sides and non-flammable blocks, could this check be modified to check for `getBlockFaceShape == BlockFaceShape.SOLID`? This would enable use of blocks like glass as walls for coke ovens and charcoal pits (I'd like it for coke ovens atleast, charcoal pits i don't care as much about, it might look a bit weird too)

(in my case it's some kind of insulated glass or iron grate block, i'm replacing the IE Coke Oven with the one from this mod, and i'd like to keep the ability to see a glowing hole to gauge whether it's active)

Thanks in advance.

**Comment by EnderiumSmith** [comment]
i didnt know that was a thing. that will make adding iron doors as valid much easier. Also do you think the texture for the burning piles look good?

**Comment by DaedalusGame** [comment]
I think it looks good enough to showcase it to the world outside the coke oven :p

**Comment by EnderiumSmith** [comment]
@DaedalusGame found a problem. the shape defaults to solid. for example my ceramic vessel counts as a valid cover. I can fix my blocks but my guess is that most mods wont know about it.

**Comment by DaedalusGame** [comment]
yeah this is a problem for many many mods, I've personally fixed this for BWM, but the best way to exorcise this problem is to just open issues whenever you see this issue in the wild. You'll know when you can place torches on odd sides of the block :)

**Comment by EnderiumSmith** [comment]
ill just revert back to isSideSolid(). you can use iron doors to see inside. and maybe ill add a list config of glass blocks.
