### ISSUE TITLE
[Question] Config coke preference item and metadata

### ISSUE THREAD

**Issue by belathus** [EnderiumSmith/CharcoalPit#5]
I didn't see a way to define meta data in the configs. I have Charcoal Pit and Immersive Engineering, but not RailCraft installed. The coke item from Immersive Engineering uses the metadata of 6. I'm trying the following:

S:CokePreference=immersiveengineering:material:6

I'm curious: how can I enter this into the configs to default to this item?

**Comment by EnderiumSmith** [comment]
there should be a CokeMeta option for the metadata, CokePreference asks just for ID

**Comment by belathus** [comment]
Oh, jeez. Yup, three lines above the CokePreference line. Got it, thanks.
