### ISSUE TITLE
Crash when attempting to use Coke Oven brick with config blocks

### ISSUE THREAD

**Issue by Mike-U5** [EnderiumSmith/CharcoalPit#50]
I tried setting Immersive Engineering's Insulating Glass as valid Coke Block.
I used the **S:CokeBlocksMeta** config option to do this.
Unfortunately, attempting to light a Coke Oven made out of insulating glass did not yield coke.
In fact, all it yielded was a game crash. Below is the crash log:

> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at charcoalPit.core.MethodHelper.CokeOvenIsValidBlock(MethodHelper.java:44)
> 	at charcoalPit.core.MethodHelper.CharcoalPitIsValidBlock(MethodHelper.java:22)
> 	at charcoalPit.tile.TileActivePile.checkValid(TileActivePile.java:64)
> 	at charcoalPit.tile.TileActivePile.func_73660_a(TileActivePile.java:38)
> 
> -- Block entity being ticked --
> Details:
> 	Name: minecraft:charcoal_pitactive_pile // charcoalPit.tile.TileActivePile
> 	Block type: ID #301 (tile.charcoal_pit:active_coal_pile // charcoalPit.blocks.BlockActivePile)
> 	Block data value: 0 / 0x0 / 0b0000
> 	Block location: World: (-172,68,273), Chunk: (at 4,4,1 in -11,17; contains blocks -176,0,272 to -161,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Actual block type: ID #301 (tile.charcoal_pit:active_coal_pile // charcoalPit.blocks.BlockActivePile)
> 	Actual block data value: 0 / 0x0 / 0b0000
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1832)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 
> -- Affected level --
> Details:
> 	Level name: New World
> 	All players: 1 total; [EntityPlayerMP['PlayerName'/1272, l='New World', x=-171.41, y=70.00, z=272.82]]
> 	Chunk stats: ServerChunkCache: 361 Drop: 0
> 	Level seed: -1491973511966572052
> 	Level generator: ID 00 - default, ver 1. Features enabled: true
> 	Level generator options: 
> 	Level spawn location: World: (-176,64,256), Chunk: (at 0,4,0 in -11,16; contains blocks -176,0,256 to -161,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 3671 game time, 3671 day time
> 	Level dimension: 0
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 164784 (now: false), thunder time: 90868 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_151, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1454634096 bytes (1387 MB) / 2026373120 bytes (1932 MB) up to 2026373120 bytes (1932 MB)
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2024m -Xmx2048m
> 	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
> 	FML: MCP 9.42 Powered by Forge 14.23.2.2637 6 mods loaded, 6 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID                   | Version      | Source                                  | Signature                                |
> 	|:--------- |:-------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                           | None                                     |
> 	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                           | None                                     |
> 	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.2.2637-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge                | 14.23.2.2637 | forge-1.12.2-14.23.2.2637-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | immersiveengineering | 0.12-80      | ImmersiveEngineering-0.12-80.jar        | 4cb49fcde3b43048c9889e0a3d083225da926334 |
> 	| UCHIJAAAA | charcoal_pit         | 1.13.2       | JCharcoalPit-[1.12]-1.13.2.jar          | None                                     |
> 
> 	Loaded coremods (and transformers): 
> IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
>   blusunrize.immersiveengineering.common.asm.IEClassTransformer
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 8; [EntityPlayerMP['PlayerName'/1272, l='New World', x=-171.41, y=70.00, z=272.82]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> [18:35:43] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# F:\MultiMC\instances\1.12.2\.minecraft\crash-reports\crash-2018-04-19_18.35.43-server.txt
> [18:35:43] [main/INFO] [FML]: Waiting for the server to terminate/save.
> [18:35:44] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
> [18:35:44] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
> [18:35:44] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/the_nether
> [18:35:44] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/the_end
> [18:35:44] [Server thread/INFO] [FML]: Unloading dimension 0
> [18:35:44] [Server thread/INFO] [FML]: Unloading dimension -1
> [18:35:44] [Server thread/INFO] [FML]: Unloading dimension 1
> [18:35:44] [Server thread/INFO] [FML]: Applying holder lookups
> [18:35:44] [Server thread/INFO] [FML]: Holder lookups applied
> [18:35:44] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
> [18:35:44] [main/INFO] [FML]: Server terminated.
> [18:35:44] [Client Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
> [18:35:44] [Client Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
> AL lib: (EE) alc_cleanup: 1 device not closed
> Process exited with code -1.

**Comment by EnderiumSmith** [comment]
-- Head --
Thread: Client thread
Stacktrace:
at charcoalPit.core.MethodHelper.CokeOvenIsValidBlock(MethodHelper.java:44)
at charcoalPit.core.MethodHelper.CharcoalPitIsValidBlock(MethodHelper.java:22)
at charcoalPit.tile.TileActivePile.checkValid(TileActivePile.java:64)
at charcoalPit.tile.TileActivePile.func_73660_a(TileActivePile.java:38)

anything below is not important but what was above was.

The problem is you put it in CokeBlocksMeta but did not specify the metadata. you need to separate the ID and meta be space. 

Also you need to be able to place a torch on the block to use it. It you cant, putting it in the config wont help. Thats why glass does not work

**Comment by Mike-U5** [comment]
Thanks, you are right, the space as the problem. I didn't notice because the examples use newlines in the config file.
