### ISSUE TITLE
Thaumcraft Hard Dependency

### ISSUE THREAD

**Issue by akmpe** [EnderiumSmith/CharcoalPit#54]
It seems version 1.15 now uses Thaumcraft as a hard dependency and the game crashes while loading unless Thaumcraft is installed.

**Comment by EnderiumSmith** [comment]
what crash?

**Comment by akmpe** [comment]
[crash-2018-05-22_01.51.47-client.txt](https://github.com/EnderiumSmith/CharcoalPit/files/2025191/crash-2018-05-22_01.51.47-client.txt)
