### ISSUE TITLE
[1.12.2] Creosote oil

### ISSUE THREAD

**Issue by TheSnowyChickens** [EnderiumSmith/CharcoalPit#57]
Hello,
I have a question about the support from Creosote oil with other mods like Thermal Foundation and IE.

On a Server with Forge 2739, CharcoalPit-[1.12]-1.16.jar, IE 84 and IR 1.3.1 I get this error:
Line 4293: [00:43:56] [Server thread/WARN] [FML]: A mod has attempted to assign Block Block{null} to the Fluid 'creosote' but this Fluid has already been linked to the Block Block{null}. You may have duplicate Fluid Blocks as a result. It may be possible to configure your mods to avoid this.
    Line 4445: [00:44:17] [Server thread/WARN] [immersiverailroading]: -203636544 7268599296

I can't disable any kind of Creosote oil from all the mods, so what can I do?
Have you any ideas?

**Comment by EnderiumSmith** [comment]
ask forge to fix it. this was not a problem in 1.7.10. try renaming the mod to load later so anothers mod creosote will be registered instead but the error is not from this mod.

**Comment by TheSnowyChickens** [comment]
Oh okay.

Thx for the issue. :)
