### ISSUE TITLE
Ash Preference not working?

### ISSUE THREAD

**Issue by TimPietsch** [EnderiumSmith/CharcoalPit#6]
Hi,

I set up the config like this:

    I:AshMeta=0
    S:AshPreference=biomesoplenty:ash

However, the charcoal pits still drop charcoal_pit:item_ash. Did I miss something/do something wrong?

**Comment by EnderiumSmith** [comment]
my guess its that biomes o plenty ash is not in the ore dictionary so the mod considers it invalid.
only items with the valid ore dict name can be used.

**Comment by TimPietsch** [comment]
Thanks for the quick answer! I'll look at the ore dictionary names when I'm home, sounds plausible though. I'll also try adding BoP ash to the ore dictionary using CraftTweaker, or would that not work?
Anyway, gonna let you know what I find out.

**Comment by TimPietsch** [comment]
I tried adding this line in CraftTweaker:

    <ore:dustAsh>.add(<biomesoplenty:ash>);

The item is registered as dustAsh in the Ore Dictionary just as expected, however, it still does not drop. Knowing neither your code nor CraftTweaker, my best guess is: could it be that Charcoal Pit determines whether a drop is valid during startup before CraftTweaker can modify things, instead of when a block is broken? Would it be feasible to add that functionality (e.g. lag)? Or is it another Ore Dictionary entry that determines validity? I don't see any other entries on charcoal_pit:item_ash.

**Comment by EnderiumSmith** [comment]
it checks on startup. checking each time a block is broken is not viable. what does biomes o plenty ash do exactly?

**Comment by TimPietsch** [comment]
Nothing much really. There are ash blocks that give off particles, it can be created into coal (I'm dialing that recipe anyway), it spawns in Nether Fortress loot chests... I mainly wanted to make my modpack consistent by having only one type of ash available and using that for all the recipe that use ash. Might as well have them coexist, no problem.

May I ask why Charcoal Pit needs the ash to be registered under dustAsh?

Thanks anyway, love the mod =)

**Comment by EnderiumSmith** [comment]
it needs oredict to make sure the item is actually ash and not some item thats named ash. biomes o plenty ash seems to be nether ash that has nothing to do with oredict ash like forestry ash.

**Comment by TimPietsch** [comment]
Yeah, it is kind of different, you're right there. Guess I'll rename it to "Nether ash" or something, thank you for the idea.
It just seems kinda weird to me, if it's mainly a balancing issue to make sure random items are produced, why it's not left to - sorry if that seems pretentious, it's by no means my intention - pack makers who are balancing with configs anyway to make sure the item is correct. Anyway, no worries. Thanks again!
