### ISSUE TITLE
[1.12.2] Furnace Light bug + more

### ISSUE THREAD

**Issue by TheSnowyChickens** [EnderiumSmith/CharcoalPit#62]
Hello,

with your Furnace:
![2018-08-19_22 35 11](https://user-images.githubusercontent.com/29357962/44312948-5b172980-a400-11e8-8fe5-234979c0af87.png)

without your Furnace:
![2018-08-19_22 37 17](https://user-images.githubusercontent.com/29357962/44312958-75510780-a400-11e8-875c-027cadc46430.png)

with your furnace on top of a block:
![2018-08-19_22 41 27](https://user-images.githubusercontent.com/29357962/44313017-1049e180-a401-11e8-8b29-ebeea04886fa.png)

below your furnace: (this is darker than normal)
![2018-08-19_22 42 28](https://user-images.githubusercontent.com/29357962/44313027-3079a080-a401-11e8-86ca-b154111c9399.png)

--------------------------------------

STRG + mouse wheel (copy block + NBT Tags) dont copy your Furnace with NBT Tags.

![2018-08-19_22 45 26](https://user-images.githubusercontent.com/29357962/44313052-c6153000-a401-11e8-9bc5-aa24d92d97ef.png)

-------------------------------------

No JEI recipe button. (usually the progress bar is this hover button)

MC 1.12.2
Forge 2747
CCP 1.17

**Comment by EnderiumSmith** [comment]
1) its a normal block. not sure why its darker.

2) it replaces it when the block is set. ill try to replace it when the item is used instead. i assume it does copy but does not read it as it places a vanilla furnace which is then replaced.

3) the other things in the mod also lack JEI integration.

**Comment by TheSnowyChickens** [comment]
Another question about JEI, I have: "DisableFurnaceOre=true", but JEI still shows me the recipes, can you add there something, that make this invisible?

**Comment by EnderiumSmith** [comment]
the reason i added a new furnace is to allow electric furnaces to still work with it. i can add a tooltip to the custom furnace.

**Comment by EnderiumSmith** [comment]
i cant fix the nbt thing.
