### ISSUE TITLE
Not an issue, just not sure what I'm doing wrong.

### ISSUE THREAD

**Issue by XvBUSHvX** [EnderiumSmith/CharcoalPit#67]
I have the mod set up in in a creative world. I have been building structures similar to the images on the project page for the Coke Oven. I have even duplicated the design, without the dropper/dispenser(?) next to the the structure. 

I have not been able to successfully use any design that includes the Iron (Trap)Door in the design. I have tried it with the doors against the coal block and with a  on the opposite side of the adjoining block space. 

I have been able to successfully produce coal coke while using sticky pistons to push blocks into position to finalize the structure, but, only if it's is a top block. When trying to make a 1x2 'door' shape on the side of the structure the coal burns up.

**Comment by EnderiumSmith** [comment]
thats weird. i have a piston door on the one i built in my survival world. it even autorefills. can you post a screenshot?

**Comment by XvBUSHvX** [comment]
These are simplistic and work after igniting the coal blocks and placing the last block of the structure above the ignited block.

![2018-08-28_13 47 44](https://user-images.githubusercontent.com/32846606/44744357-971a5080-aaca-11e8-9cd8-15d9653e980f.png)


This Style works expanding on the largest of the simple structures and triggering the piston to push the structure block above the burning coal block.

![2018-08-28_13 57 36](https://user-images.githubusercontent.com/32846606/44744493-e3fe2700-aaca-11e8-9e16-bcd1eb58356c.png)

This version does not work and destroys the coal blocks. Because there is no space above the stack of coal blocks I have to start the fire with an open space in the chamber and then place the final piece of coal and activate the pistons to push the structure blocks into place. 
![2018-08-28_13 57 41](https://user-images.githubusercontent.com/32846606/44744714-5ec74200-aacb-11e8-980a-40fe6249cc70.png)


This version however does work by combining the two previous examples. I am able to stack a full chamber of bricks and light the uppermost block before triggering the pistons and closing both the side and top portions of the structure.
![2018-08-28_13 58 05](https://user-images.githubusercontent.com/32846606/44744889-d2694f00-aacb-11e8-94ba-928f25f172fb.png)

The following, does not work and destroys the coal blocks, uses the iron door in the design which also requires lighting the coal with with an air gap before placing an additional coal block and closing the door.
![2018-08-28_14 11 57](https://user-images.githubusercontent.com/32846606/44745219-bdd98680-aacc-11e8-89ea-119fc331a893.png)

This is a variant of the previous version by placing the door from the inside on the same block space it was previously to get it closer to the coal blocks when closed. This also required starting the fire with an air gap before placing the final coal block. Still unsuccessful and destroyed the coal blocks.
![2018-08-28_14 18 45](https://user-images.githubusercontent.com/32846606/44745549-a64ecd80-aacd-11e8-95c6-71209598fa77.png)

The following is a picture following a number of trapdoor placements on the top all of which seemed to be impossible to have the door in place and light the fire without an air gap. As with the other methods that required an air gap to ignite which was later filled by a coal block it was unsuccessful and destroyed the coal block.
![2018-08-28_14 28 02](https://user-images.githubusercontent.com/32846606/44746127-1c076900-aacf-11e8-8cec-521f37e8c0fe.png)


This final one is an attempt with a trap door on the side of the structure. When closed the door is as close as it can be to the coal blocks. Again in order to light the pile I am forced to create and air gap before ignition then place the final piece of coal and close the door. Still unsuccessful and destroys all the coal.
![2018-08-28_14 34 36](https://user-images.githubusercontent.com/32846606/44746440-fd55a200-aacf-11e8-9031-12c76101c736.png)


Final observations:
Though I began this by stating there is no issue, I have began to think that there is room for some improvement in the functionality. However I am still open to how I could have built these designs to work as intended.

The only successful ignition method in my testing was with an exposed coal block at the top of the structure before closing the structure and making it whole. 

There is no apparent method of igniting the coke oven, when full, from the side of a completed structure. This requires first having an air gap above a coal block to ignite. It seems this prevents the coke oven from working as all examples of lighting with this method we unsuccessful and destroyed the coal blocks. 

This is true even if the air gap is filled with coal after igniting the exposed block and the oven sealed after ignition. This makes the use of doors and trap doors obsolete in the design of the structure. 

I did check configs to confirm that I used only materials white listed for the construction of the coke oven.

Though not as cost effective or intuitive as Iron (trap)doors would be, the most effective and convenient solution was the designed with three pistons to open and close both the side and the top.

Thanks for you time I hope this helped, feel free to ask if there is any more I could do.

It may be of benefit to allow ignition of the source even if there is not space above it coal block, or allow the air gap to be filled before checking to see if it's complete.

**Comment by EnderiumSmith** [comment]
The problem is you cant add coal blocks after you light it. All coal blocks must be there when its ignited. Iron doors work fine for me too.
![](https://i.imgur.com/LDSIX08.png)
try lighting it with a dispenser instead.
here is a simple to igniter:
![](https://i.imgur.com/h7nvDDp.png)
and a bottom igniter like in the structure above:
![](https://i.imgur.com/fDQKnZU.png)
![](https://i.imgur.com/PtfvpIO.png)

**Comment by XvBUSHvX** [comment]
That is interesting, and I tested with you designs it appears there is no way to ignite the coal with a complete structure.  But I did learn that the coal can be ignited with a fire on any exposed face, I haven't tested with under the coal but watching the Dispenser/Piston design in your example the ignition is beside the coal block before pushing the brick into position. 

I also noticed that at the time of ignition the ignited coal changes texture. I am not sure if that is a change in state of the coal block or if that is a different block entirely. 

I am researching this mod in hopes of using it in a mod pack, and would like to make it feasible for users to build a functional structure prior to redstone contraptions such as pistons, or even iron doors. For that I give my absolute thanks for the white list that allows me a lot of flexibility and design choice. 

In lieu of asking you to change your mod to facilitate me I know of other mods that would allow me to achieve my desired outcome with little to know effort from you. But I'd have to know the name of the block that the coal changes to when exposed to flame on it's surface. This way I would be able to transform a coal block by using the ignition source on it directly. 

Thanks for your time and effort.

**Comment by EnderiumSmith** [comment]
Yes it works from any side. its the fire block that activates it so it works with any mods that make fire.

Yes you need to break the shell to ignite it. Iron door support was only added recently as it needed special code so the ability to refill it without breaking blocks is new. I might add the ability to ignite it from doors since you mentioned it.

Yes the ignited blocks are different blocks.

For the modpack they can just break a block to ignite it. i assume picks will not be locked behind coke. Charcoal works with just dirt.

To find the name do /setblock ~ ~ ~ then TAB to autocomplete. Or look at the blockregistry class.
