### ISSUE TITLE
Incompatibility with Immersive Engineering

### ISSUE THREAD

**Issue by erindal** [EnderiumSmith/CharcoalPit#69]
Relevant details here: https://github.com/BluSunrize/ImmersiveEngineering/issues/3231

**Comment by paulgb434** [comment]
In charcoal_pit.cfg, the following config options exist:
B:DisableFurnaceCharcoal=true
B:DisableVanillaPottery=true
B:DisableFurnaceOre=true

If they are all set to false, it seems that the External Heater from Immersive Engineering works as intended. Although it's a workaround and not a fix, the three config options are relatively easy to replicate in CraftTweaker.

**Comment by Xorbah** [comment]
Time to learn how to use CT, then. I really want them to work hand in hand.
