### ISSUE TITLE
Glass: Solid non Flammable block doesn't work for charcoal pits?

### ISSUE THREAD

**Issue by Divineaspect** [EnderiumSmith/CharcoalPit#7]
According to the minecraft wiki glass is a solid non flammable block.
http://minecraft.gamepedia.com/Solid_block#List_of_non-solid_blocks

Is there a reason it doesn't seem to be working for the walls of a charcoal pit?

**Comment by EnderiumSmith** [comment]
its hitbox solid, not block solid. you cant put torches on it.

**Comment by Divineaspect** [comment]
cool nuf, can you  clarify that in the mod description on curseforge?
