### ISSUE TITLE
bug: charcoal pit validation doesn't read config

### ISSUE THREAD

**Issue by kreezxil** [EnderiumSmith/CharcoalPit#70]
My players wanted to watch their log piles turn into ash piles and so I added a bunch of glass ids to the config. But turns out things go invalid fast and upon inspecting your code in the MethodHelper you are not actually checking the config. But you are checking it for the bloomery and the coke oven.

**Comment by EnderiumSmith** [comment]
the config is for the coke oven, not the charcoal pit. The reason glass does not work is because its not a solid block in the sense that you cant put torches on it. I will add a config for transparent blocks next release
