### ISSUE TITLE
[Request] Being able to access clay vessels from hotbar.

### ISSUE THREAD

**Issue by G-Stav** [EnderiumSmith/CharcoalPit#72]
In the current state players must place the vessel in world to access it's GUI, fill it with items, then break it, so you can place it in a fire pit, then break it, so you can place it, and then break it again to get it's contents.

Being able to open the gui directly from your inventory would provide a smoother experience for players. 

And I do know that a way to circumvent this would be to make crafttweaker making a filled vessel through a crafting table, but I feel not only would it be disrespectful to the mod, but it would be a cheap hacky solution.

Just an idea to improve the QOL when playing with the mod. Thank you for the work you do! Great work on the mod!

**Comment by EnderiumSmith** [comment]
Ill have to figure out how. ill try adding it once i start working on the mod again
