### ISSUE TITLE
[Suggestions] Extra config options for clay vessel/ore kiln

### ISSUE THREAD

**Issue by SeriousCreeper** [EnderiumSmith/CharcoalPit#73]
Heya,

was wondering if we could some additional config options for the clay vessel: 

- Item stack size (right now you can only place 2 items in each of the 4 slots. An option to change that value would be great, i'm using ore chunks that only give a few nuggets, so having a few more of these per clay vessel would help a lot
- Specify how much fuel a ore kiln recipe requires. For example, right now i couldn't make it so that smelting down copper ore into nuggets requires no fuel (other than the heat from the kiln itself).

Think those could be added? 

Also side question, would you be okay with accepting pull requests for some of those tickets you marked as enhancement? Just to help out a bit. 

Cheers,
SC

**Comment by EnderiumSmith** [comment]
Yes i accept pull requests. Just wait until i do a commit first to fix the easier ones.
