### ISSUE TITLE
Crash / (incompatibility?) with "Charcoal Pit" mod's "Vanilla" furnace and Whopper's "Whopper"

### ISSUE THREAD

**Issue by TeetoKaziim** [EnderiumSmith/CharcoalPit#74]
https://gist.github.com/TeetoKaziim/6a93bad2a6ef4486193bac437151373d

Reproduction steps:

Install Whopper and Charcoal Pit

Place a "normal" furnace, ie the charcoal pit custom furnace.

Place a Whopper on top of the furnace, as if to feed into its input slot.

Recieve this crash.

Not sure if it's something weird on your end, or their end, so I'm dropping this in both of your issue trackers. 

Normal minecraft vanilla hoppers do not trigger this crash, or any, in the same environment.

Thanks for your time, and the mod, it's been a pleasure working and playing with it.

**Comment by EnderiumSmith** [comment]
The wopper is trying to insert nothing. When my furnace asks the oredict for the values of nothing it crashes. Im 75% sure that its their job not to insert nothing.

**Comment by TeetoKaziim** [comment]
Yeah, given that I've run into no such error with any other insertion mods with your furnace, that also would have been my guess. But, you know how it is, erring on the side of thoroughness, because if there was something "on you" to fix, it'd help to know about it.

Thanks again, and the best to ya.
