### ISSUE TITLE
Charcoal pit messes with JEI?

### ISSUE THREAD

**Issue by G-Stav** [EnderiumSmith/CharcoalPit#79]
When updating to charcoalpit[1.16.4]-2.2.jar I was having an issue that minecraft would crash when entering a world in a custom modpack. Created a new separate instance with it and jei-1.16.4-7-6-1-71.jar on forge 35.1.4 and JEI isn't visable when entering a world.

**Comment by EnderiumSmith** [comment]
i dont know why this would happen. i dont do anything weird

**Comment by EnderiumSmith** [comment]
found the problem. v2.4 should work
