### ISSUE TITLE
[suggestion] coalblock config

### ISSUE THREAD

**Issue by jonqrandom** [EnderiumSmith/CharcoalPit#9]
please will you add a config setting to allow other blocks and oredict entries to be treated as coal blocks for the purpose of making coke? charcoal pit doesn't recognise dyed coal blocks from moredyes mod (oredict as blockCoal, same as minecraft:coal_block), and quark's charcoal block (oredict as charcoalBlock).

**Comment by EnderiumSmith** [comment]
quarks charcoal block is not a coal block. you cant make coke out of charcoal. for the same reason you cant make coke out of coke.

as for dyed coal checking oredict is slower than block instance. there are not enought cases where some block would be oredicted as coal. and if you dyed your coal why would you use it to make coke?
